### ISSUE TITLE
No password length specification. Call add_user() again on wrong password

### ISSUE THREAD

**Issue by pranjal-codes** [AritificialPhysics/phonebook#12]
When the **username** , consisting of letters only, is entered , is shows that **password** did not match the specifications ..
and it terminates :'''''( . (Password is completely a/c to the specifications) 
It is supposed to just show the error and re-enter the **username**.
![buggggg](https://user-images.githubusercontent.com/50256353/90642043-87fcb200-e24f-11ea-8f98-3f3437aa8192.jpg)

**Comment by sanskar10100** [comment]
Fix the issue in the title.
